### ISSUE TITLE
Text alignment issue & missing icon and title

### ISSUE THREAD

**Issue by danipralea** [zhhlmr/ZHPopupView#3]
![simulator screen shot 27 may 2016 01 09 54](https://cloud.githubusercontent.com/assets/768893/15591785/cb9c3e06-23a7-11e6-9f93-27e5c45de86f.png)

Hello!
I have this issue where I'm not using an icon or header (there's a lot of white space on top) and also, the contentTextAlignment property is not working. (I've put it to center, but you can see that it looks funny).

Any help? I wanna know if I can keep this alert library, cause I like it.
Thanks.

**Comment by zhhlmr** [comment]
Hi there!

Thank you for pointing out this issue .
I've fix this two problems in the latest commit , pls kindly check it out . 

Have a nice day !~

Han

**Comment by danipralea** [comment]
That's absolutely great!
Thank you so much
