### ISSUE TITLE
The popupView disappeared

### ISSUE THREAD

**Issue by khalilleo** [zhhlmr/ZHPopupView#5]
Only the background color/blur shows, without the popupView, any idea how to solve this?

**Comment by zhhlmr** [comment]
@khalilleo Perhaps let me see the code ?

**Comment by khalilleo** [comment]
The example code was used

**Comment by zhhlmr** [comment]
@khalilleo Didn't adjust frames when no button is set. 
Now it's fixed, you may need to pull and update the code. I'll update it in CocoaPods later.
Thanks for pointing out the issue :)

**Comment by khalilleo** [comment]
Problem fixed! Keep up the great work!
